work_dir: ./work_dir/ntu60/xsub/agcn_rgb_joint
model_saved_name: ./runs/ntu60_cs_agcn_rgb_joint

feeder: feeders.feeder.Feeder
train_feeder_args:
  data_path: ./data/NTURGB_60/xsub/train_data_joint.npy
  label_path: ./data/NTURGB_60/xsub/train_label.pkl
  debug: False
  random_choose: False
  random_shift: False
  random_move: False
  window_size: -1
  normalization: False

train_rgb_feeder_args:
  data_path: ./data/NTURGB_60/xsub/train_data_rgb_joint.npy
  label_path: ./data/NTURGB_60/xsub/train_label.pkl
  debug: False
  random_choose: False
  random_shift: False
  random_move: False
  window_size: -1
  normalization: False

test_feeder_args:
#  data_path: ./data/NTURGB_60/xsub/val_data_joint.npy
#  label_path: ./data/NTURGB_60/xsub/val_label.pkl
  data_path: ./data/NTURGB_60/xsub/train_data_joint.npy
  label_path: ./data/NTURGB_60/xsub/train_label.pkl

test_rgb_feeder_args:
#  data_path: ./data/NTURGB_60/xsub/val_data_rgb_joint.npy
#  label_path: ./data/NTURGB_60/xsub/val_label.pkl
  data_path: ./data/NTURGB_60/xsub/train_data_rgb_joint.npy
  label_path: ./data/NTURGB_60/xsub/train_label.pkl

# model
model: model.ntu60_rgb_agcn.Model
# weights: ./runs/ntu60_cs_agcn_rgb_joint-9-6670.pt
model_args:
  num_class: 60
  num_point: 25
  num_person: 2
  graph: graph.ntu60.Graph
  graph_args:
    labeling_mode: "spatial"

#optim
weight_decay: 0.0001
base_lr: 0.1
step: [30, 40]

# training
# Update based on the nmber f GPU s available
device: [0, 1]
batch_size: 2
test_batch_size: 2
# num_epoch: 60
num_epoch: 5
nesterov: True
